### ISSUE TITLE
Better support of type definitions

### ISSUE THREAD

**Issue by CedX** [julie-ng/tidy-jsdoc#3]
I prefer to use `@typedef` for documenting options objects. But currently, the output of type definitions is not very useful: it only displays the `@type` annotation but not the `@property` ones.
It would be very cool if `@property` annotations were also displayed.

**Comment by julie-ng** [comment]
This will be fixed in version 1.0 and the results look like this:

<img width="647" alt="Screen Shot 2019-06-02 at 15 49 17" src="https://user-images.githubusercontent.com/1269507/58762934-697c9f00-8555-11e9-8fca-c71451aac59c.png">

I am showing the images because I haven't updated my library docs yet.

**Comment by CedX** [comment]
Wonderful! Thanks a lot :smile:
